### ISSUE TITLE
This exception

### ISSUE THREAD

**Issue by BarelyAPrincess** [ChioriGreene/ChioriWebServer#13]
```
[Se..Thread] 05-13 09:32:24.912 [SEVERE] [SysErr] java.lang.NoClassDefFoundError: com/mysql/jdbc/SQLError
[Se..Thread] 05-13 09:32:24.913 [SEVERE] [SysErr]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4186)
[Se..Thread] 05-13 09:32:24.913 [SEVERE] [SysErr]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)
[Se..Thread] 05-13 09:32:24.913 [SEVERE] [SysErr]   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597)
[Se..Thread] 05-13 09:32:24.913 [SEVERE] [SysErr]   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2758)
[Se..Thread] 05-13 09:32:24.913 [SEVERE] [SysErr]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2826)
[Se..Thread] 05-13 09:32:24.913 [SEVERE] [SysErr]   at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
[Se..Thread] 05-13 09:32:24.914 [SEVERE] [SysErr]   at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1302)
[Se..Thread] 05-13 09:32:24.914 [SEVERE] [SysErr]   at com.chiorichan.database.DatabaseEngine.queryUpdate(DatabaseEngine.java:352)
[Se..Thread] 05-13 09:32:24.914 [SEVERE] [SysErr]   at com.chiorichan.database.DatabaseEngine.addColumn(DatabaseEngine.java:640)
[Se..Thread] 05-13 09:32:24.914 [SEVERE] [SysErr]   at com.chiorichan.database.DatabaseEngine.addColumn(DatabaseEngine.java:603)
[Se..Thread] 05-13 09:32:24.914 [SEVERE] [SysErr]   at com.chiorichan.account.types.SqlTypeCreator.save(SqlTypeCreator.java:111)
[Se..Thread] 05-13 09:32:24.914 [SEVERE] [SysErr]   at com.chiorichan.account.AccountMeta.save(AccountMeta.java:308)
[Se..Thread] 05-13 09:32:24.915 [SEVERE] [SysErr]   at com.chiorichan.account.AccountManager.save(AccountManager.java:243)
[Se..Thread] 05-13 09:32:24.915 [SEVERE] [SysErr]   at com.chiorichan.Loader.shutdown(Loader.java:678)
[Se..Thread] 05-13 09:32:24.915 [SEVERE] [SysErr]   at com.chiorichan.ConsoleBus.run(ConsoleBus.java:111)
[Se..Thread] 05-13 09:32:24.915 [SEVERE] [SysErr]   at java.lang.Thread.run(Thread.java:745)
[Se..Thread] 05-13 09:32:24.915 [SEVERE] [SysErr] Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.SQLError
[Se..Thread] 05-13 09:32:24.915 [SEVERE] [SysErr]   at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   at java.security.AccessController.doPrivileged(Native Method)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[Se..Thread] 05-13 09:32:24.916 [SEVERE] [SysErr]   ... 16 more
```

**Comment by BarelyAPrincess** [comment]
Still can't seem to find a cause, even have tried changing the MySQL Connector version.

**Comment by BarelyAPrincess** [comment]
I think this bug as been resolved on it's own, have not witnessed it since mid-2015.
