### ISSUE TITLE
java.lang.IllegalArgumentException: Plugin already initialized!

### ISSUE THREAD

**Issue by BarelyAPrincess** [ChioriGreene/ChioriWebServer#14]
How can a plugin already be initialized when the error is being thrown on another?

```
[main      ] 05-23 13:54:09.535 [INFO] [PluginMgr] Loading the library `markdown4j-2.2.jar` from `libraries/local`...
[main      ] 05-23 13:54:09.539 [INFO] [PluginMgr] Loading the library `com.google.zxing:core:3.1.0` from file `libraries/com/google/zxing/core/3.1.0/core-3.1.0.jar`...
[main      ] 05-23 13:54:09.540 [INFO] [PluginMgr] Loading the library `com.google.zxing:javase:3.1.0` from file `libraries/com/google/zxing/javase/3.1.0/javase-3.1.0.jar`...
[main      ] 05-23 13:54:09.549 [INFO] [PluginMgr] Loading the library `javax:javaee-api:7.0` from file `libraries/javax/javaee-api/7.0/javaee-api-7.0.jar`...
[main      ] 05-23 13:54:09.567 [INFO] [PluginMgr] Loading the library `com.dropbox.core:dropbox-core-sdk:1.7.7` from file `libraries/com/dropbox/core/dropbox-core-sdk/1.7.7/dropbox-core-sdk-1.7.7.jar`...
[main      ] 05-23 13:54:09.569 [INFO] [PluginMgr] Loading the library `com.fasterxml.jackson.core:jackson-core:2.4.0` from file `libraries/com/fasterxml/jackson/core/jackson-core/2.4.0/jackson-core-2.4.0.jar`...
[main      ] 05-23 13:54:09.591 [SEVERE] [PluginMgr] Could not load 'plugins/AppleBloomHelperPlugin.jar' in folder 'plugins'
com.chiorichan.lang.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
    at com.chiorichan.plugin.loader.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:142)
    at com.chiorichan.plugin.PluginManager.loadPlugin(PluginManager.java:443)
    at com.chiorichan.plugin.PluginManager.loadPlugins(PluginManager.java:352)
    at com.chiorichan.plugin.PluginManager.loadPlugins(PluginManager.java:89)
    at com.chiorichan.Loader.start(Loader.java:366)
    at com.chiorichan.Loader.main(Loader.java:124)
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
    at com.chiorichan.plugin.loader.PluginClassLoader.initialize(PluginClassLoader.java:134)
    at com.chiorichan.plugin.loader.Plugin.<init>(Plugin.java:48)
    at co.applebloom.plugin.Helper.<init>(Helper.java:6)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:379)
    at com.chiorichan.plugin.loader.PluginClassLoader.<init>(PluginClassLoader.java:72)
    at com.chiorichan.plugin.loader.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
    ... 5 more
Caused by: java.lang.IllegalStateException: Initial initialization
    at com.chiorichan.plugin.loader.PluginClassLoader.initialize(PluginClassLoader.java:137)
    at com.chiorichan.plugin.loader.Plugin.<init>(Plugin.java:48)
    at com.chiorichan.plugin.zxing.ZxingPlugin.<init>(ZxingPlugin.java:21)
    ... 12 more
[main      ] 05-23 13:54:09.608 [INFO] [PluginMgr] Loading Template Plugin v1.2
[main      ] 05-23 13:54:09.609 [INFO] [PluginMgr] Loading ZXing Plugin v1.0
[main      ] 05-23 13:54:09.610 [INFO] [PluginMgr] Loading Email Plugin v1.0
[main      ] 05-23 13:54:09.611 [INFO] [PluginMgr] Loading Dropbox Plugin v1.0
```

**Comment by BarelyAPrincess** [comment]
I believe this problem was resolved with version 9.2.2 when the Plugin load system was changed
